name: Build Nim 👑

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: actions/setup-node@v1

    - name: Update Python PIP
      run: pip install --upgrade --disable-pip-version-check pip

    - name: Update NodeJS NPM
      run: npm install npm

    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-1.0.2

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-1.0.2

    - name: Install Nim
      if: steps.cache-choosenim.outputs.cache-hit != 'true' || steps.cache-nimble.outputs.cache-hit != 'true'
      run: |
        export CHOOSENIM_CHOOSE_VERSION="1.0.2"
        export CHOOSENIM_NO_ANALYTICS=1
        curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
        sh init.sh -y

    - name: Build project
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        # nimble build -y
        nimble test -y
