name: Build Nim 👑

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: jiro4989/setup-nim-action@v1.0.2
      with:
        nim-version: '1.2.4'

    - name: Nimble Check package validity
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nimble check

    - name: Install project
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nimble install

    - name: Unittest project
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nimble test
